version: '3.3'
services:
    budgetmaster:
        image: deadlocker8/budgetmaster-test-war:latest
        restart: "no"
        networks:
            - netPostgres
            - jenkins_dev
        expose:
          - "8080"
        ports:
          - "8080:8080"
        environment:
            TZ: Europe/Berlin
            LANG: en_US.UTF-8
            LANGUAGE: en_US.UTF-8
            budgetmaster.database.type: postgresql
            budgetmaster.database.hostname: postgres
            budgetmaster.database.port: 5432
            budgetmaster.database.databaseName: budgetmaster
            budgetmaster.database.username: budgetmaster
            budgetmaster.database.password: budgetmaster
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        restart: "no"
        environment:
            POSTGRES_DB: budgetmaster
            POSTGRES_PASSWORD: budgetmaster
            POSTGRES_USER: budgetmaster
        networks:
            - netPostgres
networks:
    netPostgres:
        driver: bridge
    jenkins_dev:
        external:
            name: jenkins_dev